# Generated by Django 4.0.4 on 2024-02-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='C:/Users/LENOVO/Desktop/shopweb/static/slider/slide1.jpg', upload_to='img.%y'),
        ),
    ]
