# Generated by Django 4.0.4 on 2024-02-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approval',
            field=models.BooleanField(default=True),
        ),
    ]
